vault file must be located in ~/.vault/

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -31,22 +31,19 @@ kill_ipport() {
 }
 
 get_vault_file() {
-  local vault="$1"
+  local vault=
+  [ -d ~/.vault ] || { mkdir -p ~/.vault && chmod 700 ~/.vault; } 
+  vault=~/.vault/$(basename $1)
   if [ ! -f "$vault" ]; then
-      [ -d ~/.vault ] || { mkdir -p ~/.vault && chmod 700 ~/.vault; } 
-      vault=~/.vault/$(basename $1)
-      if [ ! -f "$vault" ]; then
-         echo "vault file $1 or $vault not found" >&1
-         return 1
-      fi
+     echo "vault file $vault not found" >&1
+     return 1
   fi
   chmod 600 $vault
   echo $vault
 }
 
-# note: get_vault_file must be called in advance
 load_vault() {
-  local vault="$1"
+  local vault=$(get_vault_file $1)
   . $vault || { echo "fatal: load vault error." >&1; return 1; }
 }
 
diff --git a/sshforward2 b/sshforward2
--- a/sshforward2
+++ b/sshforward2
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+check_command() {
+    type $1 &> /dev/null || { echo "$1 not found." >&1; return 1; }
+}
+
+check_command expect || exit 127
+
 if [ $# -eq 0 ]; then
     echo -e "provide services in SSH forwarding tunnel"
 	echo -e "Usage:\n\t$0 <app name> <vault file>"
@@ -27,7 +33,8 @@ esac
 # test
 get_vault_file $1 || exit 1
 
-vault=$(get_vault_file $1)
+# vault file located in ~/.vault/
+vault=$(basename $1)
 
 exec /bin/bash $app $vault &
 
