add option '-i' to show connection info

diff --git a/openstack b/openstack
--- a/openstack
+++ b/openstack
@@ -30,7 +30,16 @@ fi
 
 . functions
 
-cmdline="$0 $*"
+showinfo=false
+while getopts ":i" opt; do
+    case $opt in
+      i ) showinfo=true
+          ;;
+      ? ) echo "error input"
+          exit 1;;
+    esac
+done
+shift $(($OPTIND - 1))
 
 conf="openstack.json"
 vault="$(basename $1)"
@@ -60,14 +69,22 @@ echo -e "-----------------------------------------------------------------------
 python helper.py $conf info
 echo -e "------------------------------------------------------------------------------"
 
+searchprocess="$(basename $0) $1"
 cloudman=$(python helper.py $conf info |grep ^cloudmanagement|awk '{print $2}')
 dashboard=$(python helper.py $conf info |grep ^dashboard|awk '{print $2}')
 local_forward=$(python helper.py $conf info |grep ^ssh|awk '{print $2}')
 
+if $showinfo; then
+     ps -ef |grep -E "$searchprocess|$cloudman|$local_forward" |grep -v grep
+     echo -e "\nDone."
+     exit 0
+fi
+
+cmdline="$0 $*"
+
 while true; do
     # Kill the processes that is already running
     echo "searchprocess $(basename $0) $1"
-    searchprocess="$(basename $0) $1"
 	for x in $(ps -ef |grep "$searchprocess" |grep -v grep | awk '{print $2}'); do
         if [ "$x" != "$$" ]; then
               kill $x &>/dev/null
diff --git a/redmine b/redmine
--- a/redmine
+++ b/redmine
@@ -23,7 +23,16 @@ fi
 
 . functions
 
-cmdline="$0 $*"
+showinfo=false
+while getopts ":i" opt; do
+    case $opt in
+      i ) showinfo=true
+          ;;
+      ? ) echo "error input"
+          exit 1;;
+    esac
+done
+shift $(($OPTIND - 1))
 
 conf="redmine.json"
 vault="$(basename $1)"
@@ -42,11 +51,19 @@ echo -e "-----------------------------------------------------------------------
 python helper.py $conf info
 echo -e "------------------------------------------------------------------------------"
 
+searchprocess="$(basename $0) $1"
 redmine=$(python helper.py $conf info |grep ^redmine|awk '{print $2}')
+
+if $showinfo; then
+     ps -ef |grep -E "$searchprocess|$redmine" |grep -v grep
+     echo -e "\nDone."
+     exit 0
+fi
+
+cmdline="$0 $*"
 
 while true; do
     # Kill the processes that is already running
-    searchprocess="$(basename $0) $1"
 	for x in $(ps -ef |grep "$searchprocess" |grep -v grep | awk '{print $2}'); do
         if [ "$x" != "$$" ]; then
               kill $x &>/dev/null
diff --git a/sshforward2 b/sshforward2
--- a/sshforward2
+++ b/sshforward2
@@ -9,12 +9,25 @@ check_command python || exit 127
 
 if [ $# -eq 0 ]; then
     echo -e "provide services in SSH forwarding tunnel"
-	echo -e "Usage:\n\t$0 <app name> <vault file>"
+	echo -e "Usage:\n\t$0 [-i] <app name> <vault file>"
 	echo -e "App name:"
 	echo -e  "\topenstack"
 	echo -e  "\tredmine"
+    echo -e "Options:"
+    echo -e "\t-i        show config info and exit."
 	exit 0
 fi
+
+onlyshow=
+while getopts ":i" opt; do
+    case $opt in
+      i ) onlyshow="-i"
+          ;;
+      ? ) echo "error input"
+          exit 1;;
+    esac
+done
+shift $(($OPTIND - 1))
 
 app=$1
 shift
@@ -32,10 +45,10 @@ esac
 
 . functions
 # test
-get_vault_file $1 &> /dev/null || exit 1
+get_vault_file $1 &> /dev/null || { echo "failed to get vault file: $1" >&1; exit 1; }
 
 # vault file located in ~/.vault/
 vault=$(basename $1)
 
-exec /bin/bash $app $vault &
+exec /bin/bash $app $onlyshow $vault &
 
